//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Entity
{
    public partial class TBLKULLANICI
    {
        public int KULLANICIID { get; set; }
        public string KULLANICINICK{ get; set; }
        public string KULLANICIAD { get; set; }

        public string KULLANICISOYAD { get; set; }
        public string KULLANICISIFRE { get; set; }
        public string KULLANICIMAIL { get; set; }
    }
}